[phases.setup]
nixPkgs = ["python311", "ffmpeg", "chromium", "nss", "freetype", "expat", "fontconfig"]

[phases.install]
cmds = [
    "python -m pip install -r requirements.txt",
    "playwright install chromium",
    "playwright install-deps"
]

[start]
cmd = "python main.py"
